# Generated by Django 3.2.10 on 2021-12-27 16:30

from django.db import migrations, models
import main.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='image',
            field=models.ImageField(default='', upload_to=main.utilities.get_timestamp_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(default='', upload_to=main.utilities.get_timestamp_path, verbose_name='Изображение'),
        ),
    ]
