# Generated by Django 4.0.2 on 2022-02-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_workfor_keys_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='requisites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org', models.CharField(default='', max_length=300, verbose_name='Тип организации')),
                ('inn', models.CharField(default='', max_length=300, verbose_name='ИНН')),
                ('kpp', models.CharField(default='', max_length=300, verbose_name='КПП')),
                ('company', models.CharField(default='', max_length=300, verbose_name='Юридическое название организации')),
                ('adress', models.CharField(default='', max_length=300, verbose_name='Юридический адрес')),
                ('contacts', models.CharField(default='', max_length=300, verbose_name='Контактное лицо')),
                ('email', models.CharField(default='', max_length=300, verbose_name='E-mail')),
                ('phone', models.CharField(default='', max_length=300, verbose_name='Контактный телефон')),
                ('docs', models.CharField(default='', max_length=300, verbose_name='Как будет забирать документы')),
                ('bank', models.CharField(default='', max_length=300, verbose_name='Наименование банка')),
                ('checking', models.CharField(default='', max_length=300, verbose_name='Расчетный счет')),
                ('bic', models.CharField(default='', max_length=300, verbose_name='БИК')),
                ('checkingCo', models.CharField(default='', max_length=300, verbose_name='Корреспондентский счет')),
                ('ogrn', models.CharField(default='', max_length=300, verbose_name='ОГРН')),
            ],
            options={
                'verbose_name': 'Ключь',
                'verbose_name_plural': 'Ключи',
            },
        ),
        migrations.AlterField(
            model_name='keys',
            name='date',
            field=models.DateField(blank=True, db_index=True, verbose_name='Работает до'),
        ),
    ]
