# Generated by Django 3.2.10 on 2021-12-27 17:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211227_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Текст товара'),
        ),
        migrations.AlterField(
            model_name='services',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Текст товара'),
        ),
    ]
