# Generated by Django 3.2.10 on 2021-12-31 09:34

from django.db import migrations, models
import main.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211228_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(default='', max_length=300, verbose_name='alt Изображения')),
                ('image', models.ImageField(default='', upload_to=main.utilities.get_timestamp_path, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Галерея сайта',
                'verbose_name_plural': 'Галерея сайта',
            },
        ),
    ]
