# Generated by Django 4.0.2 on 2022-03-02 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_requisites_alter_keys_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requisites',
            options={'verbose_name': 'Реквизит', 'verbose_name_plural': 'Реквизиты'},
        ),
        migrations.AddField(
            model_name='requisites',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='requisites',
            name='type',
            field=models.CharField(default='', max_length=300, verbose_name='Тип'),
        ),
        migrations.CreateModel(
            name='checks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(default='', max_length=300, verbose_name='Номер счета')),
                ('date', models.DateField(blank=True, db_index=True, verbose_name='Дата счета')),
                ('sum', models.IntegerField(default=0, verbose_name='Сумма счета')),
                ('status', models.FileField(default='', upload_to='', verbose_name='Документ')),
                ('pay', models.FileField(default='', upload_to='', verbose_name='Загрузить платежное поручение')),
                ('upd', models.FileField(default='', upload_to='', verbose_name='УПД')),
                ('owner', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Счет',
                'verbose_name_plural': 'Счета',
            },
        ),
    ]
