# Generated by Django 4.0.2 on 2022-03-02 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_requisites_options_requisites_owner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requisites',
            old_name='adress',
            new_name='address',
        ),
    ]
