# Generated by Django 3.2.10 on 2021-12-31 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='price',
            field=models.CharField(default='', max_length=300, verbose_name='Цена товара'),
        ),
    ]
