# Generated by Django 3.2.10 on 2021-12-31 12:56

from django.db import migrations, models
import django.db.models.deletion
import main.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_services_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(default='', help_text='Минимальный размер 1300x200px', upload_to=main.utilities.get_timestamp_path, verbose_name='Изображение'),
        ),
        migrations.CreateModel(
            name='photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to=main.utilities.get_timestamp_path, verbose_name='Изображение')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='main.services')),
            ],
        ),
    ]
