# Generated by Django 4.0.2 on 2022-03-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_checks_docs_alter_checks_pay_alter_checks_upd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checks',
            name='docs',
            field=models.FileField(blank=True, default='', upload_to='media/', verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='checks',
            name='pay',
            field=models.FileField(blank=True, default='', upload_to='media/', verbose_name='Загрузить платежное поручение'),
        ),
        migrations.AlterField(
            model_name='checks',
            name='upd',
            field=models.FileField(blank=True, default='', upload_to='media/', verbose_name='УПД'),
        ),
    ]
