# Generated by Django 3.2.10 on 2021-12-31 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20211231_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='image',
        ),
    ]
