# Generated by Django 3.2.10 on 2021-12-31 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_services_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pages',
            options={'verbose_name': 'Блок сайта', 'verbose_name_plural': 'Блоки сайта'},
        ),
        migrations.AlterModelOptions(
            name='photos',
            options={'verbose_name': 'Дополнительная иллюстрация', 'verbose_name_plural': 'Дополнительные иллюстрации'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
