# Generated by Django 4.0.2 on 2022-03-03 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_checks_docs_alter_checks_pay_alter_checks_upd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keys',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='Владелец'),
        ),
    ]
