# Generated by Django 4.0.2 on 2022-03-05 07:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_keys_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='helpMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=300, verbose_name='Тема письма')),
                ('email', models.EmailField(default='', max_length=300, verbose_name='Контактная почта')),
                ('question', ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Вопрос')),
                ('inv', models.FileField(blank=True, default='', upload_to='media/helps', verbose_name='Вложения')),
            ],
            options={
                'verbose_name': 'Тех. поддержка',
            },
        ),
    ]
