# Generated by Django 3.2.10 on 2022-01-10 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_photos_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='index',
            field=models.IntegerField(default=0, help_text='Чем выше индекс сортировки, тем ниже блок на сайте', verbose_name='Индекс сортировки'),
        ),
    ]
