# Generated by Django 4.0.2 on 2022-03-05 07:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_helpmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='helpmessage',
            options={'verbose_name': 'Тех. поддержка', 'verbose_name_plural': 'Тех. поддержка'},
        ),
        migrations.AlterField(
            model_name='helpmessage',
            name='question',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Вопрос'),
        ),
    ]
