# Generated by Django 4.0.2 on 2022-03-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_helpmessage_inv'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='files_helps',
            options={'verbose_name': 'Вложения', 'verbose_name_plural': 'Вложения'},
        ),
        migrations.AlterField(
            model_name='files_helps',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/help', verbose_name='Файлы'),
        ),
    ]
