# Generated by Django 4.0.2 on 2022-03-09 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_files_helps_options_alter_files_helps_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisites',
            name='hide',
            field=models.BooleanField(default=False, verbose_name='Скрыт'),
        ),
    ]
