# Generated by Django 3.2.10 on 2022-01-10 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_firstblock_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstblock',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='firstblock',
            name='image2',
        ),
    ]
