# Generated by Django 4.0.2 on 2022-03-09 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_requisites_hide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisites',
            name='hide',
            field=models.BooleanField(default=False, verbose_name='Скрытый'),
        ),
    ]
