# Generated by Django 3.2.10 on 2022-01-15 18:34

from django.db import migrations, models
import main.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20220110_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(default='', help_text='Минимальный размер 455x455px', upload_to=main.utilities.get_timestamp_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='image',
            field=models.ImageField(default='', help_text='Минимальный размер 160x160px', upload_to=main.utilities.get_timestamp_path, verbose_name='Изображение'),
        ),
    ]
