# Generated by Django 4.0.2 on 2022-03-15 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_requisites_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advuser',
            name='language',
        ),
        migrations.RemoveField(
            model_name='advuser',
            name='region',
        ),
        migrations.RemoveField(
            model_name='advuser',
            name='send_messages',
        ),
    ]
