# Generated by Django 4.0.2 on 2022-03-15 14:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_advuser_language_remove_advuser_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=300, verbose_name='Заголовок страницы')),
                ('content', ckeditor.fields.RichTextField(default='', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Другие страницы',
            },
        ),
    ]
