# Generated by Django 4.0.2 on 2022-03-15 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_pages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pages',
        ),
    ]
